### ISSUE TITLE
Stop fork - Start work!

### ISSUE THREAD

**Issue by Ant0Kr** [nikita9matveev/FansPen#2]
Hi, Guys! It's not good way for fork repo when you work in pair on your course work. @nikita9matveev try to add @dovgevgen in colobarators and work with project as equal developers:
![image](https://user-images.githubusercontent.com/17966263/35902291-b09edc98-0beb-11e8-9124-84fc224d7cb1.png)
Thnx!

**Comment by dovgevgen** [comment]
Hey, Bro! Tnks u for great advice!
